### ISSUE TITLE
Napomene testiranja - Prijava

### ISSUE THREAD

**Issue by MorenaPavlovic** [milailijevic/iooa2020-web-aplikacija#1]
Prijava:
Ako se dogodi greška korisniku je vidljivo da se   akcija nije izvršila, ali nije upozoren o kakvoj pogrešci se radi kako bi   poduzeo korake za ispravak

**Comment by milailijevic** [comment]
Prilikom prijave se ispisuje "*Pogrešan unos korisničog imena ili lozinke. Pokušajte opet!*".
