### ISSUE TITLE
Napomene testiranja - nove vrste

### ISSUE THREAD

**Issue by MorenaPavlovic** [milailijevic/iooa2020-web-aplikacija#2]
Unose nove vrste aktivnosti:
Dozvoljen je upis istih aktivnosti više puta
Ne radi funkcija brisanja aktivnosti

**Comment by milailijevic** [comment]
Bisanje radi, a aktivnost se bilježi po šifri koja je jedinstvena, dok se ostali podaci mogu ponavljati.
